apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devcontainer.pvcName" . }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "devcontainer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
