apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "antigravity.pvcName" . }}
  labels:
    {{- include "antigravity.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
