{{- if eq .Values.deploymentMode "persistent" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devcontainer.fullname" . }}
  labels:
    {{- include "devcontainer.labels" . | nindent 4 }}
spec:
  ports:
    {{- if ne (.Values.ide.type | default "vscode") "none" }}
    - port: 5800
      name: vnc-web
      protocol: TCP
      targetPort: vnc-web
    {{- end }}
    {{- if .Values.ssh.enabled }}
    - port: 22
      name: ssh
      protocol: TCP
      targetPort: ssh
    {{- end }}
  selector:
    {{- include "devcontainer.labels" . | nindent 4 }}
{{- end }}
