---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #  - configmap.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml

commonLabels:
  app: devcontainer
  environment: development

commonAnnotations:
  managed-by: kustomize
  description: "Dev Container with Happy Coder"
